senacit-inventario/app/solicitudes_traslado/solicitudes_traslado_blueprint.py
from flask import Blueprint, render_template,request,flash, redirect,url_for,session,send_file
from app.db.db import db
from app.autorizacion.autorizacon_blueprint import comprobando_autorizacion
from app.funciones_ayuda.funciones_ayuda import validar_valores_no_vacios, formatear_numero_identidad, convert_date_to_str
from app.solicitudes_traslado.forms.editar_solicitud_traslado_formulario import EditarSolicitudTrasladoFormulario
from datetime import datetime
import json
import time
import requests

#librerias de la funcion crear tabla
import os
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


#Registra el BluePrint
solicitudes_traslado_bp = Blueprint('solicitudes_traslado_bp', __name__,
    template_folder='templates',
    static_folder='static')


registro = None


#Función para descargar las imágenes que se utilizaran en el pdf
def descargar_imagen(url, max_retries=3, delay=2):
    for attempt in range(max_retries):
        try:
            response = requests.get(url)
            response.raise_for_status()
            return response.content
        except requests.RequestException as e:
            if attempt < max_retries - 1:
                print(f"Intento {attempt + 1} falló. Reintentando en {delay} segundos...")
                time.sleep(delay)
            else:
                print(f"No se pudo obtener la imagen después de {max_retries} intentos.")
                return None
            

def acortar_texto(texto, longitud_maxima=50):
    if len(texto) > longitud_maxima:
        return texto[:longitud_maxima] + '...'
    return texto


#Función para crear el pdf
def generar_pdf(datos_solicitud,imagenes):
# Crear un objeto Canvas para el PDF
    pdf_buffer = BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=letter)

    # Obtener la ruta absoluta de la imagen del logo
    directorio_ruta = os.path.dirname(os.path.abspath(__file__))
    logo_ruta = os.path.join(directorio_ruta, "static/imagenes/logo-senacit.png")

    # Verificar la existencia del archivo de logo y su formato
    if not os.path.exists(logo_ruta):
        raise FileNotFoundError(f"No se puede encontrar el archivo: {logo_ruta}")

    # Agrega el logo en la parte superior izquierda
    c.drawImage(logo_ruta, 30, 700, width=250, height=75, mask='auto')

    # Agrega el título
    c.setFont("Helvetica-Bold", 12)
    c.drawString(200, 650, "Solicitud de Traslado")  # Ajustar la posición y tamaño del título

    # Configura la fuente y tamaño de texto para el contenido de la tabla
    c.setFont("Helvetica", 10)

    # Agrega la tabla de datos
    y = 580  # Posición inicial en Y, ajustada para dejar más espacio para el título y el logo
    for campo, valor in datos_solicitud.items():
        c.drawString(100, y, campo)
        c.drawString(300, y, str(valor))
        y -= 20

    # Definir las posiciones iniciales para las imágenes
    _x = 100  # Posición inicial en X
    _y = 210  # Posición inicial en Y

    # Itera sobre las claves y valores del diccionario de imágenes
    for imagen in imagenes:
        imagen_datos = descargar_imagen(imagen["url"])
        if imagen_datos:
            # Dibujar la imagen en la posición actual
            img = ImageReader(BytesIO(imagen_datos))
            c.drawImage(img, _x, _y, width=50, height=50)
            c.drawString(_x, _y - 20, imagen["texto"])  # Agregar el texto debajo de la imagen
            
            # Ajusta las coordenadas para la próxima imagen
            _x += 150  # Aumentar la posición en X para la próxima imagen

            # Si la posición en X excede el límite, reiniciar en X y mover hacia abajo en Y
            if (_x + 50) > 500:  # Ajuste según el ancho de la imagen
                _x = 100  # Reiniciar en X
                _y -= 100  # Mover hacia abajo en Y para la próxima fila de imágenes
        else:
             print(f"No se pudo cargar la imagen: {imagen['url']}")


    # Guardar el PDF
    c.showPage()
    c.save()

    pdf_buffer.seek(0)
    return pdf_buffer.getvalue()



#Mostrar solicitudes de descargo por el número de identidad del solicitante
@solicitudes_traslado_bp.route('/descargar_pdf/<int:id_solicitud_traslado>',methods=["GET","POST"])
@comprobando_autorizacion
def descargar_pdf(id_solicitud_traslado):
    if request.method=="POST":
        try:
                print(id_solicitud_traslado)
                # Buscar solicitudes de traslado en la tabla solicitud_traslado por id_solicitud_traslado
                registro = db.mostrar_solicitudes_traslado_id_solicitud_traslado(id_solicitud_traslado)
                    
                if len(registro)==0:
                    flash("No hay registros","warning")
                    return redirect(url_for('solicitudes_traslado_bp.index'))
                                                                            
                print(registro)
                # Si hay registros se muestran en el template

                datos_solicitud_traslado = {
                    'Nombre Solicitante': registro[1],
                    'Fecha Solicitud': registro[2],
                    'Lugar': registro[4],
                    'Justificación Traslado': registro[5][:70],
                    'Número Identidad Solicitante': formatear_numero_identidad(registro[6]),
                    'Cargo': registro[9],
                    'Serie': registro[7],
                    'Color': registro[8],
                    'Número Inventario': registro[10],
                    'Descripción':registro[3][:70],
                    'Departamento Interno': registro[11],
                    'Tiempo Traslado':registro[19][:70]
            }
            
                imagenes = [
                    {'url': registro[15], "texto":"Responsable del Bien",},
                    {'url': registro[14], "texto":"Jefe Departamento",},
                    {'url': registro[16], "texto":"Jefe de Bienes",}
                ]


                pdf_data = generar_pdf(datos_solicitud_traslado,imagenes)
                #pdf_data = crear_pdf(datos_solicitud_traslado,imagenes)
                return send_file(
                        BytesIO(pdf_data),
                        mimetype='application/pdf',
                        as_attachment=True,
                        download_name='solicitud_traslado.pdf'
                    )

        except Exception as e:
                flash("No se pudo generar el pdf","warning")
                print("ERROR PDF: ",e)
                return redirect(url_for("solicitudes_traslado_bp.index"))

    else:
          return redirect(url_for("solicitudes_traslado_bp.index"))


# Editar solicitud de descargo por el número de identidad del solicitante
@solicitudes_traslado_bp.route('/editar_solicitud_traslado/<int:id_solicitud_traslado>', methods=['GET','POST'])
@comprobando_autorizacion
def editar_solicitud_traslado(id_solicitud_traslado):
    global registro
    form = EditarSolicitudTrasladoFormulario()
    
    if request.method == "POST":
        editar_solicitud_traslado = {
            "lugar": request.form["lugar"].strip(),
            "puesto": request.form["puesto"].strip(),
            "descripcion": request.form["descripcion_bien"].strip(),
            "serie": request.form["serie"].strip(),
            "justificacion_traslado": request.form["justificacion_traslado"].strip(),
            "imagen": registro[12],
            "numero_inventario": request.form["numero_inventario"],
            'firma_responsable_bien': session["url_firma_imagen"]
        }
    
        estado_valores = validar_valores_no_vacios(editar_solicitud_traslado)

        if estado_valores:
            try:
                # Asignar fechas del formulario si existen
                fecha_inicio = request.form.get('fecha_inicio')
                fecha_final = request.form.get('fecha_final')
                
                if fecha_inicio and fecha_final:
                    editar_solicitud_traslado["fecha_inicio"] = fecha_inicio
                    editar_solicitud_traslado["fecha_final"] = fecha_final
                    editar_solicitud_traslado["fecha_solicitud"] = fecha_inicio

                    # Convertir las fechas a objetos datetime
                    inicio = datetime.strptime(fecha_inicio, '%Y-%m-%d')
                    fin = datetime.strptime(fecha_final, '%Y-%m-%d')

                    # Calcular la duración en días
                    duracion = (fin - inicio).days + 1

                    # Formato de las fechas para la respuesta
                    inicio_str = inicio.strftime("%A %d de %B")
                    fin_str = fin.strftime("%A %d de %B del %Y")

                    # Crear el mensaje detallado
                    mensaje = f"El traslado se hará del {inicio_str} al {fin_str} ({duracion} días en total)."
                    editar_solicitud_traslado['mensaje'] = mensaje
                else:
                    editar_solicitud_traslado["fecha_inicio"] = registro[18]
                    editar_solicitud_traslado["fecha_final"] = registro[17]
                    editar_solicitud_traslado["fecha_solicitud"] = registro[18]
                    editar_solicitud_traslado['mensaje'] = registro[19]

                # Actualizar el registro en la base de datos
                estado_consulta = db.editar_solicitud_traslado(editar_solicitud_traslado, id_solicitud_traslado)

                if estado_consulta:
                    nombre_usuario = session["nombre_usuario"]+" "+session["apellido_usuario"]
                    detalle_actividad = json.dumps(editar_solicitud_traslado, default=convert_date_to_str)   

senacit-inventario/app/solicitudes_traslado/templates/editar_solicitud_traslado.html
{% extends 'base.html' %}
{% block title %}Editar Solicitud de Traslado{% endblock %}

{% block content %}
{% if mensaje_error %}
    <div class="alert alert-warning">
        {{ mensaje_error }}
    </div>
{% endif %}

<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.csrf_token }}

    <h4>Datos del Solicitante</h4>
    <div class="section-border">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
                <label for="lugar" class="form-label">
                    {{ form.lugar.label }}
                </label>
                {{ form.lugar(class='form-field') }}
            </div>
            <div class="form-group">
                <label for="puesto" class="form-label">
                    {{ form.puesto.label }}
                </label>
                {{ form.puesto(class='form-field') }}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
                <label for="fecha_inicio" class="form-label">
                    {{ form.fecha_inicio.label }}
                </label>
                {{ form.fecha_inicio(class='form-field') }}
            </div>
            <div class="form-group">
                <label for="fecha_final" class="form-label">
                    {{ form.fecha_final.label }}
                </label>
                {{ form.fecha_final(class='form-field') }}
            </div>
          </div>

        </div>
    </div>
    <hr><br>
    <h4>Datos del Bien y/o Materiales</h4>
    <div class="section-border">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
                <label for="numero_inventario" class="form-label">
                {{ form.numero_inventario.label }}</label> 
                {{ form.numero_inventario(class='form-field') }}
            </div>
          </div>
  
          <div class="col-md-6">
            <div class="form-group">
                <label for="serie" class="form-label">{{ form.serie.label }}</label>
                {{ form.serie(class='form-field') }}
            </div>
          </div>

          <div class="col-md-6">
            <div class="form-group">
                <label for="justificacion_descargo" class="form-label">
                {{ form.descripcion_bien.label }}</label>
                {{ form.descripcion_bien(class='form-field') }}
            </div>
            <div class="form-group">
                <label for="justificacion_traslado" class="form-label">
                {{ form.justificacion_traslado.label }}</label>
                {{ form.justificacion_traslado(class='form-field') }}
            </div>
          </div>
        </div>
    </div>
    <hr><br>

<div class="form-group">
    <button type="submit" class="btn-submit">
       <h4> Editar Solicitud Traslado </h4>
    </button>
</div>
</form>

{% endblock %}

senacit-inventario/app/solicitudes_traslado/templates/solicitudes_traslado.html
{% extends "base.html" %}

{% block title %}
  Solicitudes Traslado
{% endblock %}

{% block content %}
{% if mensaje_error %}
    <div class="alert alert-warning">
        {{ mensaje_error }}
    </div>
{% endif %}
{% if registros %}
    <h3>Mis Solicitudes [Traslado]</h3>
    <hr>
    <div class="accordion accordion-flush" id="accordionFlushExample">
    {% for registro in registros %}
        <div class="accordion-item">
        <h2 class="accordion-header" id="flush-heading{{ loop.index }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ loop.index }}" aria-expanded="false" aria-controls="flush-collapse{{ loop.index }}">
            <span class="fw-bold text-primary"> {{ registro[1] }}</span>
            </button>
        </h2>
        <div id="flush-collapse{{ loop.index }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ loop.index }}" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
                {% if registro[13]==0 %}
                    <div class="alert alert-warning">
                        <h3>Solicitud Pendiente</h3>
                    </div>
                {% else %}
                    <div class="alert alert-success">
                        <h3>Solicitud Aprobada</h3>
                    </div>
                {% endif %}               
            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre:</strong> <span class="text-primary">{{ registro[1] }}</span></li>
                <li class="list-group-item"><strong>Fecha Solicitud:</strong> <span class="text-primary">{{ registro[2] }}</span></li>
                <li class="list-group-item"><strong>Lugar:</strong> <span class="text-primary">{{ registro[4] }}</span></li>
                <li class="list-group-item"><strong>Justificación Traslado:</strong> <span class="text-primary">{{ registro[5] }}</span></li>
                <li class="list-group-item"><strong>Número de Identidad:</strong> <span class="text-primary">{{ registro[6] | formato_numero_identidad }}</span></li>
                <li class="list-group-item"><strong>Puesto:</strong> <span class="text-primary">{{ registro[9] }}</span></li>
                <li class="list-group-item"><strong>Serie:</strong> <span class="text-primary">{{ registro[7] }}</span></li>
                <li class="list-group-item"><strong>Color:</strong> <span class="text-primary">{{ registro[8] }}</span></li>
                <li class="list-group-item"><strong>Número de Inventario:</strong> <span class="text-primary">{{ registro[10] }}</span></li>
                <li class="list-group-item"><strong>Descripción:</strong> <span class="text-primary">{{ registro[3] }}</span></li>
                <li class="list-group-item"><strong>Departamento Interno:</strong> <span class="text-primary">{{ registro[11] }}</span></li>
                <li class="list-group-item"><strong>Tiempo Traslado:</strong> <span class="text-primary">{{ registro[19] }}</span></li>
                <li class="list-group-item">
                    <span class="text-primary">
                        <img src="{{ registro[12] }}" alt="cargando..." width="150" height="150">
                    </span>
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Departamento:</strong> 
                    {% if registro[14] %}
                        <span class="text-primary">
                            <img src="{{ registro[14] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item"> 
                    <strong>Firma Responsable Bien:</strong>
                    {% if registro[15] %}
                        <span class="text-primary">
                            <img src="{{ registro[15] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Bien:</strong> 
                    {% if registro[16] %}
                        <span class="text-primary">
                            <img src="{{ registro[16] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
            {% if registro[13]==0 %} 
                <li class="list-group-item">          
                        <a class="btn btn-primary" href="{{ url_for('solicitudes_traslado_bp.editar_solicitud_traslado', id_solicitud_traslado=registro[0]) }}">
                            <b>Editar Solicitud</b>
                        </a> 
                        |
                        <a class="btn btn-danger"
                        onclick="event.preventDefault(); if(confirm('¿Estás seguro de que deseas eliminar esta solicitud?')) { document.getElementById('eliminar-form-{{ registro[0] }}').submit(); }">
                          <b>Eliminar Solicitud</b>
                          </a>
                     <form id="eliminar-form-{{ registro[0] }}" action="{{ url_for('solicitudes_traslado_bp.eliminar_solicitud_traslado', id_solicitud_traslado=registro[0]) }}" method="post" style="display: none;">
                         <input type="hidden" name="_method" value="DELETE">                        
                     </form>
                </li>
            {% endif %}
                {% if registro[13]==1 %}
                    <li class="list-group-item">              
                        <a class="btn btn-primary"
                            onclick="event.preventDefault();  document.getElementById('descargar-form-{{ registro[0] }}').submit(); ">
                            <b>Descargar PDF</b>
                        </a>
                        <form id="descargar-form-{{ registro[0] }}" action="{{ url_for('solicitudes_traslado_bp.descargar_pdf',id_solicitud_traslado=registro[0])}}" method="post" style="display: none;">                       
                        </form>
                    </li>
                {% endif %}
            </ul>
            </div>
        </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <h3>No hay solicitudes</h3>
{% endif %}
{% endblock %}