senacit-inventario/app/consultas/consultas_blueprint.py
from flask import Blueprint, render_template,request,flash, redirect,url_for,send_file
from app.db.db import db
from app.consultas.forms.consultas_formulario import ConsultasFormulario
from app.autorizacion.autorizacon_blueprint import comprobando_autorizacion
import locale
from app.funciones_ayuda.funciones_ayuda import formatear_numero_identidad


#Librerías para generar el pdf
from io import BytesIO
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas


consultas_bp = Blueprint('consultas_bp', __name__,
    template_folder='templates',
    static_folder='static')


def formatear_lps(valor):
    # Configuración para la localización para el formato de números
    locale.setlocale(locale.LC_ALL, 'es_HN')

    # Convertir el valor al formato decimal
    valor_decimal = valor / 100

    # Formatear el valor para incluir la coma de los miles y el símbolo de Lempiras
    valor_formateado = locale.format_string("%.2f", valor_decimal, grouping=True)

    # Eliminar el símbolo de la moneda 'L'
    valor_formateado = valor_formateado.replace('L', '')

    # Agregar el símbolo de la moneda 'L' al inicio
    valor_formateado = 'L. ' + valor_formateado

    return valor_formateado



#Función para crear el pdf
def generar_pdf(datos_solicitud):
    # Crear un objeto Canvas para el PDF
    pdf_buffer = BytesIO()
    c = canvas.Canvas(pdf_buffer, pagesize=letter)

    # Obtener la ruta absoluta de la imagen del logo
    directorio_ruta = os.path.dirname(os.path.abspath(__file__))
    logo_ruta = os.path.join(directorio_ruta, "static/imagenes/senacit-logo.png")

    # Verificar la existencia del archivo de logo y su formato
    if not os.path.exists(logo_ruta):
        raise FileNotFoundError(f"No se puede encontrar el archivo: {logo_ruta}")
    

    # Agrega el icono en la parte superior izquierda
    c.drawImage(logo_ruta, 30, 700, width=250, height=75, mask='auto')  

    # Agrega el título
    c.setFont("Helvetica-Bold", 12)
    c.drawString(200, 650, "Información del Bien")  # Ajustar la posición y tamaño del título

    # Configura la fuente y tamaño de texto para el contenido de la tabla
    c.setFont("Helvetica", 10)

    # Agrega la tabla de datos
    y = 600  # Posición inicial en Y, ajustada para dejar más espacio para el título y el logo
    for campo, valor in datos_solicitud.items():
        c.drawString(100, y, campo)
        c.drawString(300, y, str(valor))
        y -= 20


    # Guardar el PDF
    c.showPage()
    c.save()

    pdf_buffer.seek(0)
    return pdf_buffer.getvalue()


#
@consultas_bp.route('/descargar_pdf/<string:numero_inventario>',methods=["GET","POST"])
@comprobando_autorizacion
def descargar_pdf(numero_inventario):
    if request.method=="POST":
        try:
                print(numero_inventario)
                # Buscar solicitudes de descargo en la tabla solicitud_descargo por id_solicitud_descargo
                registro = db.mostrar_registro_por_numero_inventario(numero_inventario)
                    
                if len(registro)==0:
                    flash("No hay registros","warning")
                    return redirect(url_for('consultas_bp.index'))
                                                                            
                print(registro[12])

                datos_informacion_bien = {
                    'Tipo de Documento': registro[0],
                    'Número de Documento': registro[1],
                    'Descripción del Bien': registro[2],
                    'Número de Inventario': registro[3],
                    'Modelo': registro[4],
                    'Marca': registro[5],
                    'Serie': registro[6],
                    'Placa':  registro[7],
                    'Motor': registro[8],
                    'Número de Chasis': registro[9],
                    'Color': registro[10],
                    'Departamento':  registro[11],
                    'Edificio': registro[13],
                    'Piso': registro[14],
                    'Orden de Compra': registro[15],
                    'Fecha de Ingreso': registro[16],
                    'Costo de Adquisición': formatear_lps(registro[17]),
                    'Modalidad de Contratación': registro[18],
                    'Comentario': registro[19],
                    'Estado del Bien': registro[20],
                    'Oficina': registro[21],
                    'Fecha de Documento': registro[22],
                    'Fecha de Registro del Bien': registro[23],
                    'Fecha de Registro de Inventario': registro[27],
                    'Responsable del Bien': registro[24] +" " +registro[25],
                    'Número Identidad': formatear_numero_identidad(registro[26])
            }
                
                # Crear el diccionario filtrado
                datos_informacion_bien = {
                    clave: valor for clave, valor in datos_informacion_bien.items() 
                    if clave not in ['Placa','Motor', 'Número de Chasis', 'Departamento','Orden de Compra',] or valor
                }

                if  registro[11]!="":
                    datos_informacion_bien["Municipio"] = registro[12]
                    
                pdf_data = generar_pdf(datos_informacion_bien)

                return send_file(
                        BytesIO(pdf_data),
                        mimetype='application/pdf',
                        as_attachment=True,
                        download_name='Informacion_Bien.pdf'
                    )

        except Exception as e:
                flash("No se pudo generar el pdf","warning")
                print("ERROR PDF: ",e)
                return redirect(url_for("consultas_bp.index"))

    else:
          return redirect(url_for("consultas_bp.index"))
    
    

#Mostrar solicitudes de descargo por el número de identidad del solicitante
@consultas_bp.route('/descargar_bodega_pdf/<string:numero_inventario>',methods=["GET","POST"])
@comprobando_autorizacion
def descargar_bodega_pdf(numero_inventario):
    if request.method=="POST":
        try:
                print(numero_inventario)
                # Buscar solicitudes de descargo en la tabla solicitud_descargo por id_solicitud_descargo
                registro = db.mostrar_registro_por_numero_inventario_bodega(numero_inventario)
                    
                if len(registro)==0:
                    flash("No hay registros","warning")
                    return redirect(url_for('consultas_bp.index'))
                                                                            
                print(registro[12])

                datos_informacion_bien = {
                    'Tipo de Documento': registro[0],
                    'Número de Documento': registro[1],
                    'Descripción del Bien': registro[2][:70],
                    'Número de Inventario': registro[3],
                    'Modelo': registro[5],
                    'Serie': registro[6],
                    'Color': registro[10],     
                    'Edificio': registro[13],
                    'Piso': registro[14],
                    'Orden de Compra': registro[15],
                    'Fecha de Ingreso': registro[16],
                    'Costo de Adquisición': formatear_lps(registro[17]),
                    'Modalidad de Contratación': registro[18],
                    'Comentario': registro[19][:70],
                    'Estado del Bien': registro[20],
                    'Oficina': registro[21],
                    'Fecha de Documento': registro[22],
                    'Fecha de Registro del Bien': registro[24],
                    'Fecha de Registro en Bodega': registro[23]
            }

                # Crear el diccionario filtrado
                datos_informacion_bien = {
                    clave: valor for clave, valor in datos_informacion_bien.items() 
                    if clave not in ['Placa', 'Modalidad de Contratación', 'Motor', 'Número de Chasis', 'Departamento','Orden de Compra'] or valor
                }

                if  registro[11]!="":
                    datos_informacion_bien["Municipio"] = registro[12]

                pdf_data = generar_pdf(datos_informacion_bien)

                return send_file(
                        BytesIO(pdf_data),
                        mimetype='application/pdf',
                        as_attachment=True,
                        download_name='Informacion_Bien[Bodega].pdf'
                    )

        except Exception as e:
                flash("No se pudo generar el pdf","warning")
                print("ERROR PDF: ",e)
                return redirect(url_for("consultas_bp.index"))

    else:
          return redirect(url_for("consultas_bp.index"))
    



@consultas_bp.route('/buscar_registro_numero_inventario', methods=['GET', 'POST'])
@comprobando_autorizacion
def buscar_registro_numero_inventario():
    form = ConsultasFormulario()
    if request.method == "POST":
        numero_inventario = request.form["numero_inventario"].strip()
        
        # Depuración adicional
        print("NÚMERO DE INVENTARIO RECIBIDO: ", numero_inventario, type(numero_inventario))

        if numero_inventario == "":
            flash("Debes ingresar el número de inventario", 'warning')
            return redirect(url_for('consultas_bp.index'))

        try:
            # Asegúrate de que numero_inventario sea una cadena
            numero_inventario = str(numero_inventario)
            
            # Depuración adicional antes de la consulta
            print("NÚMERO DE INVENTARIO PARA CONSULTA: ", numero_inventario, type(numero_inventario))
            

senacit-inventario/app/consultas/templates/consultar.html
{% extends "base.html" %}

{% block title %}
    Consultar Bienes
{% endblock %}

{% block content %}
    <h1>Consultar Bienes</h1>
    <hr>
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4 mb-3">
                <form method="POST" action="{{ url_for('consultas_bp.buscar_registro_numero_inventario') }}">
                    <div class="form-group">
                        <label for="numero_inventario" class="form-label">
                            {{ form.numero_inventario.label }}
                        </label>
                        {{ form.numero_inventario(class='form-control') }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">
                        Consultar
                    </button>
                </form> 
            </div>
            <div class="col-md-4 mb-3">
                <form method="POST" action="{{ url_for('consultas_bp.buscar_registro_numero_inventario_bodega') }}">
                    <div class="form-group">
                        <label for="numero_inventario_bodega" class="form-label">
                            {{ form.numero_inventario_bodega.label }}
                        </label>
                        {{ form.numero_inventario_bodega(class='form-control', aria_label='Número de inventario de bodega') }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">
                        Consultar
                    </button>
                </form> 
            </div>
            <div class="col-md-4 mb-3">
                <form method="POST" action="{{ url_for('consultas_bp.buscar_registro_numero_identidad') }}">       
                    <div class="form-group">
                        <label for="numero_identidad" class="form-label">
                            {{ form.numero_identidad.label }}
                        </label>
                        {{ form.numero_identidad(class='form-control', aria_label='Número de identidad') }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">
                        Consultar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

senacit-inventario/app/consultas/templates/mostrar_registro.html
  {% extends "base.html" %}

  {% block title %}
      Registro Inventario
  {% endblock %}


  {% block content %}
    <h1>Información del Bien</h1><hr><br> 

    {% set imagenes_bien = registro[28] | cadena_diccionario %}
      <table class="table table-bordered table-striped">
          <tr>
              <th scope="row">Tipo de Documento</th>
              <td>{{ registro[0] }}</td>
            </tr>
            <tr>
              <th scope="row">Número de Documento</th>
              <td>{{ registro[1] }}</td>
            </tr>
            <tr>
              <th scope="row">Descripción del Bien</th>
              <td>{{ registro[2] }}</td>
            </tr>
            <tr>
              <th scope="row">Número de Inventario</th>
              <td>{{ registro[3] }}</td>
            </tr>
            <tr>
              <th scope="row">Modelo</th>
              <td>{{ registro[4] }}</td>
            </tr>
            <tr>
              <th scope="row">Marca</th>
              <td>{{ registro[5] }}</td>
            </tr>
            <tr>
              <th scope="row">Serie</th>
              <td>{{ registro[6] }}</td>
            </tr>
            {% if registro[7] %}
              <tr>
                <th scope="row">Placa</th>
                <td>{{ registro[7] }}</td>
              </tr>
            {% endif %}
            {% if registro[8] %}
              <tr>
                <th scope="row">Motor</th>
                <td>{{ registro[8] }}</td>
              </tr>
            {% endif %}
            {% if registro[9] %}
              <tr>
                <th scope="row">Número de Chasis</th>
                <td>{{ registro[9] }}</td>
              </tr>
            {% endif %}
            <tr>
              <th scope="row">Color</th>
              <td>{{ registro[10] }}</td>
            </tr>
            {% if registro[11] %}
              <tr>
                <th scope="row">Departamento</th>
                <td>{{ registro[11] }}</td>
              </tr>
              <tr>
                <th scope="row">Municipio</th>
                <td>{{ registro[12] }}</td>
              </tr>
            {% endif %}
            <tr>
              <th scope="row">Edificio</th>
              <td>{{ registro[13] }}</td>
            </tr>
            <tr>
              <th scope="row">Piso</th>
              <td>{{ registro[14] }}</td>
            </tr>
            {% if registro[15] %}
              <tr>
                <th scope="row">Orden de Compra</th>
                <td>{{ registro[15] }}</td>
              </tr>
            {% endif %}
            <tr>
              <th scope="row">Fecha de Ingreso</th>
              <td>{{ registro[16] }}</td>
            </tr>
            <tr>
              <th scope="row">Costo de Adquisición</th>
              <td>{{ registro[17] | formatear_lps }}</td>
            </tr>
            <tr>
              <th scope="row">Modalidad de Contratación</th>
              <td>{{ registro[18] }}</td>
            </tr>
            <tr>
              <th scope="row">Comentario</th>
              <td>{{ registro[19] }}</td>
            </tr>
            <tr>
              <th scope="row">Estado del Bien</th>
              <td>{{ registro[20] }}</td>
            </tr>
            <tr>
              <th scope="row">Oficina</th>
              <td>{{ registro[21] }}</td>
            </tr>
            <tr>
              <th scope="row">Fecha de Documento</th>
              <td>{{ registro[22] }}</td>
            </tr>
            <tr>
              <th scope="row">Fecha de Registro del Bien</th>
              <td>{{ registro[23] }}</td>
            </tr>
            <tr>
              <th scope="row">Fecha de Registro de Inventario</th>
              <td>{{ registro[27] }}</td>
            </tr>
            <tr>
              <th scope="row">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalImagenes">
                  <b> Ver Imágenes</b>
                </button>
              </th>
            </tr>
            <tr>
              <th scope="row">
              <a class="btn btn-primary"
                onclick="event.preventDefault();  document.getElementById('descargar-form-{{ registro[0] }}').submit(); ">
                <b>Descargar PDF</b>
            </a>
            <form id="descargar-form-{{ registro[0] }}" action="{{ url_for('consultas_bp.descargar_pdf', numero_inventario=registro[3])}}" method="post" style="display: none;">                       
            </form>
              </th>
            </tr>
      </table>
      <br>
    <h1>Datos del Usuario</h1>
      <table class="table table-bordered table-striped">
        <tr>
            <th scope="row">Nombre</th>
            <td>{{ registro[24] }}</td>
        </tr>
        <tr>
          <th scope="row">Apellido</th>
          <td>{{ registro[25] }}</td>
      </tr>
      <tr>
          <th scope="row">Número de Identidad</th>
          <td>{{ registro[26] | formato_numero_identidad }}</td>
      </tr>
    </table>

    
      <!-- Modal de Bootstrap 5 para las imágenes -->
    <div class="modal fade" id="modalImagenes" tabindex="-1" aria-labelledby="modalImagenesLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalImagenesLabel">Imágenes</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Carrusel Bootstrap para las imágenes -->
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            {% for imagen in imagenes_bien %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img src="{{ imagen.secure_url}}" class="d-block w-100" alt="Imagen {{ loop.index }}">
                                </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">anterior</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">siguiente</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {% endblock %}

senacit-inventario/app/consultas/templates/mostrar_registro_bodega.html
{% extends "base.html" %}

{% block title %}
    Registro en Bodega
{% endblock %}

{% block content %}
  <h1>Información del Bien en Bodega</h1><hr><br> 

  {% set imagenes_bien = registro[25] | cadena_diccionario %}
  <table class="table table-bordered table-striped">
      <tr>
          <th scope="row">Tipo de Documento</th>
          <td>{{ registro[0] }}</td>
      </tr>
      <tr>
          <th scope="row">Número de Documento</th>
          <td>{{ registro[1] }}</td>
      </tr>
      <tr>
          <th scope="row">Descripción del Bien</th>
          <td>{{ registro[2] }}</td>
      </tr>
      <tr>
          <th scope="row">Número de Inventario</th>
          <td>{{ registro[3] }}</td>
      </tr>
      <tr>
          <th scope="row">Modelo</th>
          <td>{{ registro[4] }}</td>
      </tr>
      <tr>
          <th scope="row">Marca</th>
          <td>{{ registro[5] }}</td>
      </tr>
      <tr>
          <th scope="row">Serie</th>
          <td>{{ registro[6] }}</td>
      </tr>
      {% if registro[7] %}
        <tr>
          <th scope="row">Placa</th>
          <td>{{ registro[7] }}</td>
        </tr>
      {% endif %}
      {% if registro[8] %}
        <tr>
          <th scope="row">Motor</th>
          <td>{{ registro[8] }}</td>
        </tr>
      {% endif %}
      {% if registro[9] %}
        <tr>
          <th scope="row">Número de Chasis</th>
          <td>{{ registro[9] }}</td>
        </tr>
      {% endif %}
      <tr>
          <th scope="row">Color</th>
          <td>{{ registro[10] }}</td>
      </tr>
      {% if registro[11] %}
        <tr>
          <th scope="row">Departamento</th>
          <td>{{ registro[11] }}</td>
        </tr>
        <tr>
          <th scope="row">Municipio</th>
          <td>{{ registro[12] }}</td>
        </tr>
      {% endif %}
      <tr>
          <th scope="row">Edificio</th>
          <td>{{ registro[13] }}</td>
      </tr>
      <tr>
          <th scope="row">Piso</th>
          <td>{{ registro[14] }}</td>
      </tr>
      {% if registro[15] %}
      <tr>
          <th scope="row">Orden de Compra</th>
          <td>{{ registro[15] }}</td>
      </tr>
      {% endif %}
      <tr>
          <th scope="row">Fecha de Ingreso</th>
          <td>{{ registro[16] }}</td>
      </tr>
      <tr>
          <th scope="row">Costo de Adquisición</th>
          <td>{{ registro[17] | formatear_lps }}</td>
      </tr>
      {% if registro[18] | default('') %}
        <tr>
          <th scope="row">Modalidad Contratación</th>
          <td>{{ registro[18] }}</td>
        </tr>
      {% endif %}
      <tr>
          <th scope="row">Comentario</th>
          <td>{{ registro[19] }}</td>
      </tr>
      <tr>
          <th scope="row">Estado del Bien</th>
          <td>{{ registro[20] }}</td>
      </tr>
      <tr>
          <th scope="row">Oficina</th>
          <td>{{ registro[21] }}</td>
      </tr>
      <tr>
          <th scope="row">Fecha de Documento</th>
          <td>{{ registro[22] }}</td>
      </tr>
      <tr>
          <th scope="row">Fecha de Registro del Bien</th>
          <td>{{ registro[24] }}</td>
      </tr>
      <tr>
          <th scope="row">Fecha de Registro de Bodega</th>
          <td>{{ registro[23] }}</td>
      </tr>
      <tr>
        <th scope="row">
            <!-- Button to trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalImagenes">
                <b>Ver Imágenes</b>
            </button>
        </th>
    </tr>
    <tr>
        <th scope="row">
            <a class="btn btn-primary"
            onclick="event.preventDefault();  document.getElementById('descargar-form-{{ registro[0] }}').submit(); ">
            <b>Descargar PDF</b>
        </a>
        <form id="descargar-form-{{ registro[0] }}" action="{{ url_for('consultas_bp.descargar_bodega_pdf', numero_inventario=registro[3])}}" method="post" style="display: none;">                       
        </form>
        </th>
        
  </table>
  <br>

  <!-- Modal de Bootstrap 5 para las imágenes -->
  <div class="modal fade" id="modalImagenes" tabindex="-1" aria-labelledby="modalImagenesLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalImagenesLabel">Imágenes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Carrusel Bootstrap para las imágenes -->
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for imagen in imagenes_bien %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img src="{{ imagen.secure_url}}" class="d-block w-100" alt="Imagen {{ loop.index }}">
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">anterior</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">siguiente</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

senacit-inventario/app/consultas/templates/mostrar_registros.html
{% extends "base.html" %}

{% block title %}
    Registros Ingresados
{% endblock %}


{% block content %}
<h3>Total Bienes [{{ total_registros }}]</h3>
<h3>Monto Total: {{ monto_total | formatear_lps }} </h3>
<hr> <br>
<div class="accordion accordion-flush" id="accordionFlushExample">
  {% for registro in registros %}
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-heading{{ loop.index }}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ loop.index }}" aria-expanded="false" aria-controls="flush-collapse{{ loop.index }}">
          <span class="fw-bold text-primary">{{ registro[0] }} {{ registro[1] }}</span>
        </button>
      </h2>
      <div id="flush-collapse{{ loop.index }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ loop.index }}" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          <ul class="list-group">
            <li class="list-group-item"><strong>Nombre:</strong> <span class="text-primary">{{ registro[0] }}</span></li>
            <li class="list-group-item"><strong>Apellido:</strong> <span class="text-primary">{{ registro[1] }}</span></li>
            <li class="list-group-item"><strong>Número de Identidad:</strong> <span class="text-primary">{{ registro[2] | formato_numero_identidad }}</span></li>
            <li class="list-group-item"><strong>Fecha Registro Inventario:</strong> <span class="text-primary">{{ registro[3] }}</span></li>
            <li class="list-group-item"><strong>Fecha Ingreso Bien:</strong> <span class="text-primary">{{ registro[4] }}</span></li>
            <li class="list-group-item"><strong>Fecha Ingreso:</strong> <span class="text-primary">{{ registro[5] }}</span></li>
            <li class="list-group-item"><strong>Fecha Documento:</strong> <span class="text-primary">{{ registro[6] }}</span></li>
            <li class="list-group-item"><strong>Número de Documento:</strong> <span class="text-primary">{{ registro[7] }}</span></li>
            <li class="list-group-item"><strong>Descripción:</strong> <span class="text-primary">{{ registro[8] }}</span></li>
            <li class="list-group-item"><strong>Número de Inventario:</strong> <span class="text-primary">{{ registro[9] }}</span></li>
            <li class="list-group-item"><strong>Tipo de Documento:</strong> <span class="text-primary">{{ registro[10] }}</span></li>
            <li class="list-group-item"><strong>Modelo:</strong> <span class="text-primary">{{ registro[11] }}</span></li>
            <li class="list-group-item"><strong>Serie:</strong> <span class="text-primary">{{ registro[12] }}</span></li>
            <li class="list-group-item"><strong>Marca:</strong> <span class="text-primary">{{ registro[13] }}</span></li>
            {% if registro[14] %}
            <li class="list-group-item"><strong>Placa:</strong> <span class="text-primary">{{ registro[14] }}</span></li>
            {% endif %}
            {% if registro[15] %}
            <li class="list-group-item"><strong>Motor:</strong> <span class="text-primary">{{ registro[15] }}</span></li>
            {% endif %}
             {% if registro[16] %}
            <li class="list-group-item"><strong>Número de Chasis:</strong> <span class="text-primary">{{ registro[16] }}</span></li>
            {% endif %}
            <li class="list-group-item"><strong>Color:</strong> <span class="text-primary">{{ registro[17] }}</span></li>
            {% if registro[18] %}
            <li class="list-group-item"><strong>Departamento:</strong> <span class="text-primary">{{ registro[18] }}</span></li>
            {% endif %}
            {% if registro[19] !="None" %}
            <li class="list-group-item"><strong>Municipio:</strong> <span class="text-primary">{{ registro[19] }}</span></li>
            {% endif %}
            <li class="list-group-item"><strong>Departamento Interno:</strong> <span class="text-primary">{{ registro[20] }}</span></li>
            <li class="list-group-item"><strong>Edificio:</strong> <span class="text-primary">{{ registro[21] }}</span></li>
            <li class="list-group-item"><strong>Piso:</strong> <span class="text-primary">{{ registro[22] }}</span></li>
            {% if registro[23] %}
            <li class="list-group-item"><strong>Orden de Compra:</strong> <span class="text-primary">{{ registro[23] }}</span></li>
            {%endif %}
            <li class="list-group-item"><strong>Costo de Adquisición:</strong> <span class="text-primary">{{ registro[24] | formatear_lps }}</span></li>
            <li class="list-group-item"><strong>Modalidad de Contratación:</strong> <span class="text-primary">{{ registro[25] }}</span></li>
            <li class="list-group-item"><strong>Comentario:</strong> <span class="text-primary">{{ registro[26] }}</span></li>
            <li class="list-group-item"><strong>Estado del Bien:</strong> <span class="text-primary">{{ registro[27] }}</span></li>
            <li class="list-group-item"><strong>Oficina:</strong> <span class="text-primary">{{ registro[28] }}</span></li>
      
          </ul>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}




