senacit-inventario/app/revisar_solicitudes_descargo/revisar_solicitudes_descargo_blueprint.py

from flask import Blueprint, render_template,request,url_for,redirect,flash,session
from app.db.db import db
from app.autorizacion.autorizacon_blueprint import comprobando_autorizacion, \
 es_tecnico
from app.funciones_ayuda.funciones_ayuda import validar_valores_no_vacios
import textwrap

revisar_solicitudes_descargo_bp = Blueprint('revisar_solicitudes_descargo_bp', __name__,
    template_folder='templates',
    static_folder='static')


#Ruta principal
@revisar_solicitudes_descargo_bp.route('/', methods=["GET", "POST"])
@es_tecnico
@comprobando_autorizacion
def index():
        es_jefe_departamento = session['es_jefe_departamento']
        departamento_interno = session['departamento_interno']
        es_tecnico = session['es_tecnico']

        if es_jefe_departamento == 1:
            print("es jefe")
            try:
                if departamento_interno!="Bienes":
                    registros = db.mostrar_solicitudes_descargo_jefe_departamento(departamento_interno)
                    if registros is None:
                        return render_template('revisar_solicitudes_descargo.html')
                                           
                    print(registros)
                    # Si se encuentra el registro, redirigir a la página de edición con los datos del registro
                    return render_template('revisar_solicitudes_descargo.html', 
                                            registros=registros, es_jefe_departamento=True)
                else:
                    registros = db.mostrar_solicitudes_descargo()

                    if registros is None:
                        return render_template('revisar_solicitudes_descargo.html')
                                           
                    print(registros)
                    # Si se encuentra el registro, redirigir a la página de edición con los datos del registro
                    return render_template('revisar_solicitudes_descargo.html', 
                                        registros=registros,aprobar_solicitud=True,es_jefe_departamento_bienes=True)
            except Exception as e:
                # Muestra error si  hay
                return render_template("revisar_solicitudes_descargo.html", mensaje_error="Vuelve a intentarlo.")
  
        elif es_tecnico==1:
            try:
                # Buscar solicitudes de descargo en la tabla solicitud_descargo
                registros = db.mostrar_solicitudes_descargo_tenico_departamento(departamento_interno)
                
                if len(registros)==0:
                    return render_template('revisar_solicitudes_descargo.html')
                                                                        
                print(registros)
                # Si se encuentra el registro, redirigir a la página de edición con los datos del registro
                return render_template('revisar_solicitudes_descargo.html', 
                                        registros=registros, generar_dictamen=True)
            except Exception as e:
                # Muestra error si no hay
                return render_template("revisar_solicitudes_descargo.html", mensaje_error="Vuelve a intentarlo.")
        

#Funcion agrega la firma del jefe de departamento
@revisar_solicitudes_descargo_bp.route('/agregar_firma', methods=["GET","POST"])
@es_tecnico
@comprobando_autorizacion
def agregar_firma():
    if request.method=="POST":
        id_solicitud_descargo =  request.form.get('id_solicitud_descargo')
        if not session.get("url_firma_imagen"):
            flash("Debes ingresar tu firma",'warning')
            return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
        
        datos_editar = {
            "firma_jefe_departamento": session["url_firma_imagen"]
        }

        if id_solicitud_descargo:
           estado_solicitud = db.editar_solicitud_descargo(datos_editar,id_solicitud_descargo)
           if estado_solicitud:
               flash("Enhorabuena se ha agregado tu firma",'success')
               return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
           else:
               flash("Vuelve a intentarlo",'warning')
               return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
        else:
                flash("Vuelve a intentarlo",'warning')
                return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
    else:
        return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
    


#Funcion aprobar el dictamen de la solicitude de desacargo
@revisar_solicitudes_descargo_bp.route('/aprobar_solicitud', methods=["GET","POST"])
@es_tecnico
@comprobando_autorizacion
def aprobar_solicitud():
    if request.method == "POST":
        id_solicitud_descargo = request.form.get('id_solicitud_descargo')
        if not session.get("url_firma_imagen"):
            flash("Debes ingresar tu firma",'warning')
            return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
        
        registro = db.mostrar_solicitudes_descargo_id_solicitud_descargo(id_solicitud_descargo)
        print(registro)

        datos_editar = {
            "firma_jefe_unidad_bien": session["url_firma_imagen"],
            "estado_solicitud": 1
        }

        firma_jefe_departamento = registro[16]
        firma_responsable_dictamen = registro[17]
        firma_responsable_bien = registro[18]

        if firma_jefe_departamento and firma_responsable_dictamen and firma_responsable_bien and id_solicitud_descargo:
            estado_solicitud = db.aprobar_solicitud_descargo(datos_editar, id_solicitud_descargo)
            if estado_solicitud:
                flash("Enhorabuena, se ha aprobado la solicitud", 'success')
            else:
                flash("No se pudo aprobar la solicitud. Por favor, inténtalo de nuevo.", 'warning')
        else:
            if not id_solicitud_descargo:
                flash("ID de solicitud de descargo no proporcionado.", 'warning')
            flash("Faltan firmas para poder aprobar la solicitud.", 'warning')
        
        return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
    else:
        return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
    

def formatear_descripcion(contenido):
    lineas = textwrap.wrap(contenido, width=25)
    return '\n'.join(lineas)


#Funcion agregar el dictaen de infotecnologia
@revisar_solicitudes_descargo_bp.route('/agregar_dictamen', methods=["GET","POST"])
@es_tecnico
@comprobando_autorizacion
def agregar_dictamen():
    if request.method=="POST":
        id_solicitud_descargo =  request.form.get('id_solicitud_descargo')
        if not session.get("url_firma_imagen"):
            flash("Debes ingresar tu firma",'warning')
            return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
        
        descripcion =  formatear_descripcion(request.form.get('descripcion'))
        diagnostico =  request.form.get('diagnostico')


        datos_editar = {
            "descripcion": descripcion,
            "diagnostico": diagnostico,
            "firma_responsable_dictamen":session["url_firma_imagen"],
            "numero_identidad_responsable_dictamen":session["codigo_usuario"]
        }

        print(datos_editar)
       
        estado_campos_vacios = validar_valores_no_vacios(datos_editar)
        if estado_campos_vacios:
           estado_solicitud = db.agregar_dictamen_solicitud_descargo(datos_editar,id_solicitud_descargo)
           if estado_solicitud:
               flash("Enhorabuena se ha agregado tu dictamen",'success')
               return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
           else:
               flash("Vuelve a intentarlo",'warning')
               return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
        else:
            
               flash("Debes ingresar los datos",'warning')
               return redirect(url_for('revisar_solicitudes_descargo_bp.index'))
    else:
        return redirect(url_for('revisar_solicitudes_descargo_bp.index'))

senacit-inventario/app/revisar_solicitudes_descargo/templates/revisar_solicitudes_descargo.html
{% extends "base.html" %}

{% block title %}
    Revisar Solicitudes
{% endblock %}

{% block content %}
{% if mensaje_error %}
    <div class="alert alert-warning">
        {{ mensaje_error }}
    </div>
{% endif %}
{% if registros %}
    <hr>
        <h3>Solicitudes sin Aprobar [Descargo]</h3>
   
    <div class="accordion accordion-flush" id="accordionFlushExample">

    {% for registro in registros %}
        {% if registro[15]==0 %}

        <div class="accordion-item">
        <h2 class="accordion-header" id="flush-heading{{ loop.index }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ loop.index }}" aria-expanded="false" aria-controls="flush-collapse{{ loop.index }}">
            <span class="fw-bold text-primary"> {{ registro[1] }}</span>
            </button>
        </h2>
        <div id="flush-collapse{{ loop.index }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ loop.index }}" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre:</strong> <span class="text-primary">{{ registro[1] }}</span></li>
                <li class="list-group-item"><strong>Fecha Solicitud:</strong> <span class="text-primary">{{ registro[2] }}</span></li>
                <li class="list-group-item"><strong>Lugar:</strong> <span class="text-primary">{{ registro[3] }}</span></li>
                <li class="list-group-item"><strong>Justificación Descargo:</strong> <span class="text-primary">{{ registro[4] }}</span></li>
                <li class="list-group-item"><strong>Número de Identidad:</strong> <span class="text-primary"> {{ registro[5] | formato_numero_identidad }} </span></li>
                <li class="list-group-item"><strong>Puesto:</strong> <span class="text-primary">{{ registro[6] }}</span></li>
                <li class="list-group-item"><strong>Marca:</strong> <span class="text-primary">{{ registro[7] }}</span></li>
                <li class="list-group-item"><strong>Serie:</strong> <span class="text-primary">{{ registro[8] }}</span></li>
                <li class="list-group-item"><strong>Número de Inventario:</strong> <span class="text-primary">{{ registro[9] }}</span></li>
                {% if registro[10] %}
                    <li class="list-group-item"><strong>Diagnóstico:</strong> <span class="text-primary">{{ registro[10] }}</span></li>
                {% endif %}
                <li class="list-group-item"><strong>Modelo:</strong> <span class="text-primary">{{ registro[11] }}</span></li>
                {% if registro[12] %}
                    <li class="list-group-item"><strong>Descripción:</strong> <span class="text-primary">{{ registro[12] }}</span></li>
                {% endif %}
                <li class="list-group-item"><strong>Departamento Interno:</strong> <span class="text-primary">{{ registro[13] }}</span></li>
                <li class="list-group-item">
                    <span class="text-primary">
                        <img src="{{ registro[14] }}" alt="cargando..." width="150" height="150">
                    </span>
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Departamento:</strong> 
                    {% if registro[16] %}
                        <span class="text-primary">
                            <img src="{{ registro[16] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <strong>Firma Responsable Dictamen:</strong> 
                        {% if registro[17] %}
                        <span class="text-primary">
                            <img src="{{ registro[17] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item"> 
                    <strong>Firma Responsable Bien:</strong>
                    {% if registro[18] %}
                        <span class="text-primary">
                            <img src="{{ registro[18] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Bienes:</strong> 
                    {% if registro[19] %}
                        <span class="text-primary">
                            <img src="{{ registro[19] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                {% if es_jefe_departamento %}
                    <li class="list-group-item">
                        <form action="{{ url_for('revisar_solicitudes_descargo_bp.agregar_firma') }}" method="POST">
                            <input type="hidden" name="id_solicitud_descargo" value="{{registro[0]}}">
                            <button type="submit" class="btn btn-primary">Agregar Firma</button>
                        </form>
                    </li>
                {% endif %}
                {% if es_jefe_departamento_bienes %}
                    <li class="list-group-item">
                        <form action="{{ url_for('revisar_solicitudes_descargo_bp.agregar_firma') }}" method="POST">
                            <input type="hidden" name="id_solicitud_descargo" value="{{registro[0]}}">
                            <button type="submit" class="btn btn-primary">Agregar Firma</button>
                        </form>
                    </li>
                {% endif %}
                {% if aprobar_solicitud %}
                    <li class="list-group-item">
                        <form action="{{ url_for('revisar_solicitudes_descargo_bp.aprobar_solicitud') }}" method="POST">
                            <input type="hidden" name="id_solicitud_descargo" value="{{registro[0]}}">
                            <button type="submit" class="btn btn-primary">Aprobar Solicitud</button>
                        </form>
                    </li>
                {% endif %}
                {% if generar_dictamen %}
                    <li class="list-group-item">
                        <form action="{{ url_for('revisar_solicitudes_descargo_bp.agregar_dictamen') }}" method="POST">
                            <input type="hidden" name="id_solicitud_descargo" value="{{registro[0]}}">
                            <div class="form-group">
                                <label for="diagnostico"><strong>Diagnóstico</strong></label>
                                <input type="text" class="form-control" id="diagnostico" name="diagnostico">
                            </div>
                            <div class="form-group">
                                <label for="descripcion"><strong>Descripción</strong></label>
                                <textarea class="form-control" id="descripcion" name="descripcion" rows="4"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Enviar Dictamen</button>
                        </form>
                    </li>
                {% endif %}
            </ul>
            </div>
        </div>
        </div>
      {% endif %}
    {% endfor %}
  <br> <hr>
    <div class="alert alert-success">
        <h3>Solicitudes Aprobadas</h3>
    </div>
    {% for registro in registros %}
        {% if registro[15]==1 %}

        <div class="accordion-item">
        <h2 class="accordion-header" id="flush-heading{{ loop.index }}">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ loop.index }}" aria-expanded="false" aria-controls="flush-collapse{{ loop.index }}">
            <span class="fw-bold text-primary"> {{ registro[1] }}</span>
            </button>
        </h2>
        <div id="flush-collapse{{ loop.index }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ loop.index }}" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre:</strong> <span class="text-primary">{{ registro[1] }}</span></li>
                <li class="list-group-item"><strong>Fecha Solicitud:</strong> <span class="text-primary">{{ registro[2] }}</span></li>
                <li class="list-group-item"><strong>Lugar:</strong> <span class="text-primary">{{ registro[3] }}</span></li>
                <li class="list-group-item"><strong>Justificación Descargo:</strong> <span class="text-primary">{{ registro[4] }}</span></li>
                <li class="list-group-item"><strong>Número de Identidad:</strong> <span class="text-primary">{{ registro[5] | formato_numero_identidad }}</span></li>
                <li class="list-group-item"><strong>Puesto:</strong> <span class="text-primary">{{ registro[6] }}</span></li>
                <li class="list-group-item"><strong>Marca:</strong> <span class="text-primary">{{ registro[7] }}</span></li>
                <li class="list-group-item"><strong>Serie:</strong> <span class="text-primary">{{ registro[8] }}</span></li>
                <li class="list-group-item"><strong>Número de Inventario:</strong> <span class="text-primary">{{ registro[9] }}</span></li>
                <li class="list-group-item"><strong>Diagnóstico:</strong> <span class="text-primary">{{ registro[10] }}</span></li>
                <li class="list-group-item"><strong>Modelo:</strong> <span class="text-primary">{{ registro[11] }}</span></li>
                <li class="list-group-item"><strong>Descripción:</strong> <span class="text-primary">{{ registro[12] }}</span></li>
                <li class="list-group-item"><strong>Departamento Interno:</strong> <span class="text-primary">{{ registro[13] }}</span></li>
                <li class="list-group-item">
                    <span class="text-primary">
                        <img src="{{ registro[14] }}" alt="cargando..." width="150" height="150">
                    </span>
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Departamento:</strong> 
                    {% if registro[16] %}
                        <span class="text-primary">
                            <img src="{{ registro[16] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <strong>Firma Responsable Dictamen:</strong> 
                        {% if registro[17] %}
                        <span class="text-primary">
                            <img src="{{ registro[17] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item"> 
                    <strong>Firma Responsable Bien:</strong>
                    {% if registro[18] %}
                        <span class="text-primary">
                            <img src="{{ registro[18] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <strong>Firma Jefe Bienes:</strong> 
                    {% if registro[19] %}
                        <span class="text-primary">
                            <img src="{{ registro[19] }}" alt="cargando..." width="150" height="150">
                        </span>
                    {% endif %}
                </li>

            </ul>
            </div>
        </div>
        </div>
      {% endif %}
    {% endfor %}
    </div>
    </div>
{% else %}
    <h3>No hay solicitudes</h3>
{% endif %}
{% endblock %}